# Generated by Django 3.2 on 2021-05-25 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('comment', models.IntegerField()),
            ],
        ),
    ]
