# Generated by Django 3.2 on 2021-04-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('purpose', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent'), ('Lease', 'Lease')], max_length=50)),
                ('photo', models.ImageField(blank='True', upload_to='photo/%Y/%m/%d/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('room', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20)),
            ],
        ),
    ]
