# Generated by Django 3.2 on 2021-04-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, choices=[('lagos', 'lagos'), ('Abuja', 'Abuja'), ('Enugu', 'Enugu'), ('Portharcourt', 'Portharcourt')], max_length=20),
        ),
    ]
